# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20161103_0509'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='isOpen',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
