# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 06:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_course_isopen'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='module',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='course.Module'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='component',
            name='order_no',
            field=models.PositiveSmallIntegerField(default=2),
            preserve_default=False,
        ),
    ]
