# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20161104_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='contents',
            field=models.FileField(upload_to='files'),
        ),
        migrations.AlterField(
            model_name='image',
            name='contents',
            field=models.ImageField(upload_to='images'),
        ),
    ]
