# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 23:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_auto_20161104_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='name',
            field=models.CharField(default='image', max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(default='file', max_length=1024),
            preserve_default=False,
        ),
    ]
