# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 23:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_auto_20161104_2345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='name',
        ),
        migrations.RemoveField(
            model_name='image',
            name='name',
        ),
    ]
