# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-05 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_auto_20161104_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='contents',
            field=models.FileField(upload_to='files/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='image',
            name='contents',
            field=models.ImageField(upload_to='images/%Y/%m/%d'),
        ),
    ]
