# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-05 12:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_auto_20161105_0523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='isOpen',
            new_name='is_open',
        ),
    ]
