# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 03:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_auto_20161106_0255'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Component')),
                ('module_progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.ModuleProgress')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Status')),
            ],
        ),
    ]
