# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 08:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_componentprogress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='componentprogress',
            name='component',
        ),
        migrations.RemoveField(
            model_name='componentprogress',
            name='module_progress',
        ),
        migrations.RemoveField(
            model_name='componentprogress',
            name='status',
        ),
        migrations.AlterField(
            model_name='moduleprogress',
            name='enrolled_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.EnrolledCourse'),
        ),
        migrations.DeleteModel(
            name='ComponentProgress',
        ),
    ]
