# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_auto_20161107_0635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolledcourse',
            name='completion_date',
            field=models.DateTimeField(null=True),
        ),
    ]
