# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='usernmae',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
