# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 18:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20161030_1321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='role_id',
            new_name='role',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='usernmae',
            new_name='username',
        ),
    ]
