# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-05 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20161030_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='Default Name', max_length=200),
            preserve_default=False,
        ),
    ]
